### ISSUE TITLE
谷歌商店里的应用

### ISSUE THREAD

**Issue by zhongheng666** [ghostry/toAria2#5]
楼主啥时候更新下谷歌商店里的应用，你的这个插件很好用，但谷歌商店里很久没更新了，楼主什么时候计划更新下呢

**Comment by ghostry** [comment]
更新不了了，商店是别人代传的，现在联系不到人了。

**Comment by ghostry** [comment]
@LoveyCat  增加了本地安装的方法.

**Comment by zhongheng666** [comment]
Thanks
