### ISSUE TITLE
提示插件尚未配置

### ISSUE THREAD

**Issue by treadpit** [ghostry/toAria2#6]
如题，Aria2在本地，已配置：
![image](https://user-images.githubusercontent.com/10692855/31372930-a6ce6860-ad5d-11e7-880b-8f9d4b477f45.png)

点击下载，弹出框提示：
![image](https://user-images.githubusercontent.com/10692855/31372969-d160c4c4-ad5d-11e7-96a8-dde4f0cc1ef1.png)

请问这个是什么问题呢，是哪里没配置么？

**Comment by ghostry** [comment]
这种情况一般重启chrome就行了.

**Comment by treadpit** [comment]
@ghostry 好的
