### ISSUE TITLE
不支持 rpc-passwd 加密？

### ISSUE THREAD

**Issue by yimiaoxiehou** [ghostry/toAria2#9]
我的 aria2 加密了，在 YAAW 和 百度云插件 baiduexporter 中都按照 http://token:passwd@127.0.0.1:6800/jsonrpc 的方式配置，前端都可以连接上。
但是在 toAria2 中，我相同配置下载时却提示插件未配置？
请问，如何解决

**Comment by ysmintor** [comment]
期待解决这个问题

**Comment by ghostry** [comment]
确实未支持加密

**Comment by Chilkings** [comment]
期待解决加密问题，要用远程机器的aria2，总不能不设置密码吧

**Comment by ghostry** [comment]
> 期待解决加密问题，要用远程机器的aria2，总不能不设置密码吧

https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn

我已经用这个了.支持加密.

除了不能选文字添加,别的都很好.

**Comment by ghostry** [comment]
已增加支持 token
